[package]
name = "rust_shortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
postgres = "0.19.7"
nanoid = "0.4.0"
url = "2.5.0"