[default]
port = 8001
address = "::"

[default.databases.local_url_shortener]
# Hostname is the name of the service in the docker-compose file
url = "postgres://postgres:local_url_shortener@rust_shortener-db-1:5432/postgres"